apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  labels:
    app: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo-app
        image: demo.goharbor.io/demo/java-app:1.0
        ports:
        - containerPort: 8080