apiVersion: argoproj.io/v1alphal
kind: Application
metadata:
  name: java-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/renwu58/argcd-demo-app.git
    targetRevision: HEAD
    path: dev/demo-app
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true